/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#484847",
        "secondary": "#10d5ff",
        "tertiary-container": "#599cf9",
        "primary-fixed-dim": "#00d4ec",
        "inverse-primary": "#006976",
        "secondary-fixed": "#78dfff",
        "surface-variant": "#262626",
        "inverse-surface": "#fcf9f8",
        "surface": "#0e0e0e",
        "on-primary-fixed": "#003840",
        "surface-tint": "#81ecff",
        "on-tertiary-fixed": "#001835",
        "tertiary-fixed": "#80b2ff",
        "surface-container-low": "#131313",
        "on-primary-container": "#004d57",
        "tertiary-dim": "#5c9ffc",
        "on-secondary-fixed": "#003a47",
        "tertiary-fixed-dim": "#65a4ff",
        "on-secondary": "#004554",
        "primary-dim": "#00d4ec",
        "on-surface": "#ffffff",
        "error-container": "#9f0519",
        "surface-dim": "#0e0e0e",
        "error": "#ff716c",
        "on-surface-variant": "#adaaaa",
        "on-tertiary": "#002a55",
        "surface-container-highest": "#262626",
        "secondary-container": "#00677d",
        "primary-fixed": "#00e3fd",
        "inverse-on-surface": "#565555",
        "on-error-container": "#ffa8a3",
        "on-primary-fixed-variant": "#005762",
        "primary-container": "#00e3fd",
        "on-secondary-container": "#edfaff",
        "on-error": "#490006",
        "surface-container-lowest": "#000000",
        "on-primary": "#005762",
        "background": "#0e0e0e",
        "surface-bright": "#2c2c2c",
        "primary": "#81ecff",
        "on-tertiary-fixed-variant": "#003971",
        "surface-container": "#1a1a1a",
        "secondary-fixed-dim": "#10d5ff",
        "error-dim": "#d7383b",
        "on-background": "#ffffff",
        "secondary-dim": "#00c6ee",
        "surface-container-high": "#20201f",
        "tertiary": "#70aaff",
        "outline": "#767575",
        "on-secondary-fixed-variant": "#00586b",
        "on-tertiary-container": "#001d3f"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"],
        "inter": ["Inter", "sans-serif"],
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}